### ISSUE TITLE
Pré-tese - GAMA

### ISSUE THREAD

**Issue by naps62** [ampereira/mscthesis-liptool#1]
Vou eu a ler a tua secção sobre o GAMA, e fico logo desiludido na primeira linha

`The GAMA [1] framework is a tool similar to OpenACC`

Isto não é nada correcto. Basta veres o exemplo de código do GAMA para ver a diferença. O OpenACC é á base de pragmas, e é suposto ser de muito alto nivel, e abstrair os detalhes da arquitectura
O GAMA é exactamente o oposto. Podes generalizar se possivel, mas também tens controlo para programar o kernel especificamente para cada dispositivo. E precisas de coisas como o método de dicing. O objectivo é mesmo ter o maximo possivel de performance, e não abstrair a dificuldade de programação

**Comment by naps62** [comment]
`It frees the programmer from managing the workload
distribution, memory usage and data transfers between the available resources.`

Isto também não é inteiramente verdade

**Comment by ampereira** [comment]
ok, a segunda parte ai já tirei quase de tacada do manual....

2013/2/2 Miguel Palhas notifications@github.com
