### ISSUE TITLE
SPAM

### ISSUE THREAD

**Issue by naps62** [ampereira/mscthesis-liptool#2]
já punhas o raio do openmp a funcionar

**Comment by pfac** [comment]
Boa tarde,

No passado sábado perdi uma virgindade no BA. Dado ser algo com muito valor sentimental, peço a quem a tiver encontrado que a devolva, ou pelo menos as memórias.

Boa noite e obrigado.

**Comment by ampereira** [comment]
Já estou quase a bater em alguém. Como garantir synch apos cada iteração
dum parallel for?

No dia 18 de Março de 2013 à49 10:35, Pedro Costa
notifications@github.comescreveu:

**Comment by pfac** [comment]
#pragma omp barrier?

**Comment by pfac** [comment]
é oficial, tamos os 3 na merda

**Comment by ampereira** [comment]
nope, não posso dentro do for... whyyy reductions whyyy... e aposto que
esta merda não vai ser muito melhor -_-

2013/3/18 Pedro Costa notifications@github.com

**Comment by naps62** [comment]
When I find myself in times of trouble,
**pereira's thesis** comes to me,
Speaking words of **trouble**,
Let it be.
And in the hour of darkness,
He is standing **even worse than me**, 
Speaking words of **trouble**,
Let it be.

**Comment by pfac** [comment]
parece-me estranho não poderes dentro do for, mas se for para verificares o estado do programa, põe um contador partilhado, no início da iteração a master põe a zero, depois onde quiseres sincronizar pões todas as threads a incrementar uma vez e depois prende-as num while (counter != num_threads)

+9999 para o naps pelo poema

**Comment by pfac** [comment]
e faz um atomic à volta do incremento, senão tens uma race condition

**Comment by ampereira** [comment]
FUCKKKKK SOU TAO ESTUPIDO ELAS TEM TODAS DE INCREMENTAR NAO POSSO
PARALELIZAR O FOR

/caps off

2013/3/18 Pedro Costa notifications@github.com

**Comment by pfac** [comment]
não percebi mas parece que ajudei. yay me

**Comment by ampereira** [comment]
O pereira a pensar em algoritmos paralelos para implementar

[image: Imagem intercalada 1]

2013/3/18 Pedro Costa notifications@github.com

**Comment by pfac** [comment]
não se vê caralhos...

**Comment by ampereira** [comment]
quem é que ta a entupir os hex? preciso de coisos para acabar com o spam!

2013/3/18 Pedro Costa notifications@github.com

**Comment by naps62** [comment]
a julgar pelo qstat, uns tais de pawelpil e pyrlinsv

**Comment by naps62** [comment]
faz-te homem e vai para os nodos 100. Assim sempre podes ter finalmente algum speedup quando voltares a mudar

**Comment by naps62** [comment]
a serio que ainda andas a fazer commits sobre esta coisa?
